### ISSUE TITLE
순위 화면 구현

### ISSUE THREAD

**Issue by Heosejin98** [Heosejin98/xmash-app#2]
현재 메인페이지만 구현되어있음 아래 화면을 app 버전 순위에 해당하는 화면 구현

![image](https://github.com/user-attachments/assets/e6e17d02-19ae-4bdc-a788-acd84fcf8256)

![image](https://github.com/user-attachments/assets/b092d032-48ed-412f-b56e-90eae9993a8b)

**Comment by 2Yebeen** [comment]
<img width="580" alt="스크린샷 2024-11-16 오후 6 07 57" src="https://github.com/user-attachments/assets/8a6e3153-65af-4028-8290-f4afe1ecb963">
